// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `catch`, `decode_asset_id`, `decode_message`, `to_sources`

/// The Nightjar address, `ak` and `nkc` for `seed` on `network`.
///
/// The Nightjar derivation is not ZIP 32 and takes no account index, so all of this wallet's
/// accounts on one seed share one Nightjar identity.
Future<NjIdentity> nightjarIdentity({
  required List<int> seed,
  required String network,
}) => RustLib.instance.api.crateApiNightjarNightjarIdentity(
  seed: seed,
  network: network,
);

/// The `channel_id` a published UIVK names on `network`, as lowercase hex.
///
/// Useful on its own: it is what a caller checks the indexer's `/api/status` against before
/// believing a single message it serves, because an indexer pointed at another channel would
/// otherwise answer every query perfectly and about the wrong thing.
Future<String> nightjarChannelId({
  required String network,
  required String channelUivk,
}) => RustLib.instance.api.crateApiNightjarNightjarChannelId(
  network: network,
  channelUivk: channelUivk,
);

/// The canonical (final) height at `chain_tip` for a channel with this birthday: `tip − 10`,
/// floored at the block before the birthday.
///
/// Exposed so the UI can say "n blocks until this is final" with the same arithmetic the replay
/// uses, rather than a second copy of the constant in Dart that could drift from it.
Future<int> nightjarCanonicalHeight({
  required int chainTip,
  required int birthday,
}) => RustLib.instance.api.crateApiNightjarNightjarCanonicalHeight(
  chainTip: chainTip,
  birthday: birthday,
);

/// Replay a channel and report what `seed` owns in it.
///
/// Every Groth16 proof in `messages` is verified against `vk`, every signature is checked, and
/// the commitment tree, nullifier set and asset registry are rebuilt from scratch. The resulting
/// `state_root` is directly comparable with the one any other verifier publishes for the same
/// height — comparing them is how a caller detects an indexer that withheld a message, which is
/// the one thing this cut cannot prevent. That comparison is only worth making because every
/// `msg_id` is recomputed from its own body first: `msg_id` is folded into `state_root` and is
/// covered by no proof, so an id taken on the source's word let the source pick the root. A
/// message whose id its body does not produce fails this call outright.
///
/// `vk_hash` on the result is the hash of the key the proofs were checked against, for a caller
/// that wants to pin it against `/api/status` or against a second source.
///
/// `chain_tip` decides the height the view is closed at, so it must be a real chain tip and not
/// the highest message height: the anchor set is pruned as a function of that height and is
/// folded into `state_root`, so a channel that has been quiet for more than 200 blocks produces
/// a different root at its last message than at the tip. Prefer the tip this wallet's own
/// lightwalletd sync reports over the indexer's.
///
/// ZEC-claim messages (order fills) are **not** verified: checking one needs the carrying Zcash
/// transaction, which this path never sees, so they are ignored with a reason rather than
/// treated as having passed. An order fill will not show up in `notes`.
///
/// # Reading the history back out of `notes`
///
/// `notes` is every note this wallet has ever owned on the channel, spent ones included and
/// marked, each naming the message that created it and the message that spent it. Group by
/// `msg_id` and one message's worth of this wallet's side of a transition is in hand. What that
/// supports, and what it does not:
///
/// - **A payment this wallet authored.** Every note with `spent_by == M` is an input it owned.
///   If that count equals `spent_inputs`, this wallet owned *all* of `M`'s inputs and therefore
///   signed it. What left is `sum(inputs) − sum(outputs owned)`, where the outputs owned are the
///   notes with `created_by == M`; the rest of that sum is change and must not be shown as a
///   receipt.
/// - **A receipt.** No note has `spent_by == M`, and some note has `created_by == M`. The amount
///   received is the sum of those notes.
/// - **A transition this wallet only partly funded** — it owns some but not `spent_inputs` of
///   the inputs. A `buy` or a `fill` is exactly this: maker's note and taker's note in one
///   transition, neither party alone the author. `sum(inputs owned) − sum(outputs owned)` is
///   this wallet's net change in that message and is meaningful; calling it "sent" is not.
///   Compare the two counts before choosing a verb.
/// - **What cannot be decided at all**: how much went to whom. When a message owns more outputs
///   than this wallet holds (`created_outputs` exceeds the number of notes naming it), the
///   remainder is addressed to keys this wallet has not got and its amounts are not small or
///   zero — they are unknowable from this data. A recipient address is likewise nowhere in this
///   struct: it is inside a ciphertext only the recipient can open. "Paid *someone* this much"
///   is derivable; "paid this address" is not.
///
/// Four further shapes are worth naming because they read like something they are not:
///
/// - **paying yourself**, which is legal and is what consolidating two notes into one looks
///   like. Every output is this wallet's, so `sum(inputs) − sum(outputs owned)` is zero and the
///   arithmetic above calls it a payment of nothing. It is one; the money did not leave. There
///   is no field that distinguishes it from a payment to a stranger that happened to have no
///   recipient, because there is no such payment — a zero difference *is* the self-payment case.
/// - **a `recovered` note** (a covenant payout or a remainder) arrives in a transition this
///   wallet very likely did not sign, so the rule above files it as a receipt, which it is.
/// - **a `published` note** is dated by its creating transition, not by the `NOTE` message that
///   disclosed it, so it can appear in the history at a height well before this wallet could
///   have learnt of it.
/// - **a payment this wallet has just made is not here at all.** The view is closed at
///   `tip − 10`, so for those ten blocks neither the spend nor its change exists: the input
///   still counts as unspent and the balance is the old one. `preview_messages` is the only
///   signal that this is happening, and a send screen that does not say so will look like it
///   lost the money and then made it reappear.
Future<NjView> nightjarReplay({
  required String network,
  required String channelUivk,
  required int birthday,
  required int chainTip,
  required List<int> vk,
  required List<NjMessageInput> messages,
  required List<int> seed,
  required NjZecSources zecSources,
}) => RustLib.instance.api.crateApiNightjarNightjarReplay(
  network: network,
  channelUivk: channelUivk,
  birthday: birthday,
  chainTip: chainTip,
  vk: vk,
  messages: messages,
  seed: seed,
  zecSources: zecSources,
);

/// Validate a Nightjar proving-key folder and report what is in it.
///
/// Reads the 1.8 KiB verifying key and the one-line sidecar manifest and `stat`s the 83 MiB
/// proving key — it does not load it, so this is cheap enough to run whenever a settings screen
/// opens. Every error is a sentence meant to be shown verbatim.
///
/// Call it before offering to send. The alternative is discovering a wrong or missing key after
/// a replay and a review screen, at the one moment the user has already decided to pay.
Future<NjProvingKey> nightjarCheckProvingKey({required String keysDir}) =>
    RustLib.instance.api.crateApiNightjarNightjarCheckProvingKey(
      keysDir: keysDir,
    );

/// Turn "pay `amount` base units of `asset_id` to `recipient`" into the memos that carry it.
///
/// **This function does not broadcast, and it does not touch the network.** It returns memo
/// bytes. Putting them on chain is the caller's next step and it is this wallet's ordinary send
/// path: one `RawSendOutput` per entry of `NjPayPlan.memos`, every one addressed to the
/// *channel's* unified address (not the Nightjar recipient — a Nightjar address has no Zcash
/// receiver), every one carrying `NjPayPlan.memo_value_zatoshi`, all of them in the single call
/// to `proposeSendRaw` so they share one txid, then `executeProposal`. Splitting them across two
/// transactions produces fragments nobody can reassemble and value that is simply gone.
///
/// It replays the channel first, through the same code path as `nightjar_replay` — every
/// `msg_id` rebound to its body, every proof verified, the state closed at `tip − 10` — because
/// a payment is proved against that state's tree root. Pass the same `messages`, `vk`,
/// `birthday` and `chain_tip` the read path was given; a plan built against a state this wallet
/// did not verify would name an anchor the rest of the channel does not have.
///
/// `keys_dir` is the folder holding `interpreter-v0.pk`, `.vk` and `.circuit`. Validate it with
/// [`nightjar_check_proving_key`] when the settings screen loads: here, a missing or
/// wrong-circuit folder is refused before the replay, and a folder whose key set is not the one
/// the channel verifies with is refused after it.
///
/// Costs: the replay is seconds, the proof about 1.3 s and ~600 MB of peak memory. Call it off
/// the UI isolate and show progress. The proving key is read and dropped inside this call and is
/// never cached, so that peak is transient rather than a permanent floor.
///
/// Amounts are integer base units of the asset. `NjAsset.decimals` is applied to a display
/// string by the UI and to nothing here.
Future<NjPayPlan> nightjarBuildPay({
  required String network,
  required String channelUivk,
  required int birthday,
  required int chainTip,
  required List<int> vk,
  required List<NjMessageInput> messages,
  required List<int> seed,
  required String keysDir,
  required String assetId,
  required BigInt amount,
  required String recipient,
  required NjZecSources zecSources,
}) => RustLib.instance.api.crateApiNightjarNightjarBuildPay(
  network: network,
  channelUivk: channelUivk,
  birthday: birthday,
  chainTip: chainTip,
  vk: vk,
  messages: messages,
  seed: seed,
  keysDir: keysDir,
  assetId: assetId,
  amount: amount,
  recipient: recipient,
  zecSources: zecSources,
);

/// An asset on the channel, joined with this wallet's balance of it.
class NjAsset {
  final String assetId;

  /// The collection the issuing transition named, or **empty when not disclosed** — same
  /// reason as `max_supply` below. It is never an all-zero hash: that is a collection id like
  /// any other and saying it here would be a claim, not an absence.
  final String collectionId;

  /// Position inside `collection_id`, or `None` when no applied *public* issuance disclosed
  /// one — the same absence `collection_id` reports as empty.
  ///
  /// It comes from the issuing transition's `terms`, which is hashed into `asset_id`, so it is
  /// a fact about the chain rather than a label anyone chose. A collection's metadata document
  /// resolves `item.image`'s `{index}` with it (`spec/asset-collection-v0.md` section 3.2), and
  /// that substitution is safe *only* because of that binding — which is why this crosses the
  /// FFI at all instead of the document's own idea of an index being trusted on the Dart side.
  final int? index;

  /// True when an applied *public* issuance put this asset's supply on the channel. False is
  /// the privately issued case: the asset is listed because this wallet holds a note of it,
  /// and `issued`, `collection_id` and `max_supply` are all undisclosed rather than zero.
  final bool public;

  /// Empty when no `ASSET` message has named the asset; unnamed is not invalid.
  final String name;
  final String symbol;

  /// A display hint only. No arithmetic on this path applies it.
  final int decimals;
  final String uri;

  /// Outstanding public supply. Meaningless unless `public`: a private issuance publishes no
  /// amount, and `0` there means "the channel does not know", not "none exists".
  final BigInt issued;

  /// The supply cap the issuing transition declared, where `Some(0)` means uncapped, as on the
  /// wire.
  ///
  /// `None` is **not disclosed**, and it is the normal case for a privately issued asset: the
  /// cap lives in the body of the issuing message, and a private issuance publishes no such
  /// body for the channel to read. Reporting `0` there would say "uncapped" about an asset
  /// whose cap nobody on this channel can see.
  final BigInt? maxSupply;

  /// What this wallet holds **now**, in integer units: spent notes are not counted, however
  /// much of the history `notes` carries. This number did not change when spent notes joined
  /// that list, and a caller summing `notes` itself must filter on `NjNote::spent` to agree
  /// with it.
  final BigInt balance;

  /// How many **unspent** notes make up `balance`. It is not `notes.length` for this asset.
  final int noteCount;

  const NjAsset({
    required this.assetId,
    required this.collectionId,
    this.index,
    required this.public,
    required this.name,
    required this.symbol,
    required this.decimals,
    required this.uri,
    required this.issued,
    this.maxSupply,
    required this.balance,
    required this.noteCount,
  });

  @override
  int get hashCode =>
      assetId.hashCode ^
      collectionId.hashCode ^
      index.hashCode ^
      public.hashCode ^
      name.hashCode ^
      symbol.hashCode ^
      decimals.hashCode ^
      uri.hashCode ^
      issued.hashCode ^
      maxSupply.hashCode ^
      balance.hashCode ^
      noteCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NjAsset &&
          runtimeType == other.runtimeType &&
          assetId == other.assetId &&
          collectionId == other.collectionId &&
          index == other.index &&
          public == other.public &&
          name == other.name &&
          symbol == other.symbol &&
          decimals == other.decimals &&
          uri == other.uri &&
          issued == other.issued &&
          maxSupply == other.maxSupply &&
          balance == other.balance &&
          noteCount == other.noteCount;
}

/// The Nightjar identity a wallet seed carries: what to show on a receive screen.
class NjIdentity {
  /// Bech32m, prefixed `nj` / `njtest` / `njreg` by network.
  final String address;
  final String ak;
  final String nkc;

  const NjIdentity({
    required this.address,
    required this.ak,
    required this.nkc,
  });

  @override
  int get hashCode => address.hashCode ^ ak.hashCode ^ nkc.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NjIdentity &&
          runtimeType == other.runtimeType &&
          address == other.address &&
          ak == other.ak &&
          nkc == other.nkc;
}

/// One reassembled message as `/api/messages?body=1` reports it.
///
/// None of it is believed. `msg_id` is recomputed from `kind`, `fragments` and `body` under the
/// channel id and must match, which is what makes the other fields safe to act on.
class NjMessageInput {
  /// Lowercase hex, 32 bytes.
  final String msgId;
  final int kind;

  /// Completion location. A message above `tip − 10` is preview and is dropped by the replay;
  /// the caller may hand it over anyway and read `preview_messages` back. A message *below* the
  /// channel birthday is refused outright — no reference verifier replays that block.
  final int height;
  final int txIndex;
  final int actionIndex;

  /// The indexer's `fragments`: how many memo fragments carried this body.
  ///
  /// Required, and required to be right, because it is hashed into `msg_id` along with `kind`
  /// and `body`. Pass the field verbatim; do not reconstruct it from `body.length`.
  final int fragments;

  /// The indexer's `txid` for the Zcash transaction that completed this message, lowercase hex
  /// in display order. Empty is allowed and means "not supplied".
  ///
  /// **A fetch key, not evidence.** Nothing in the protocol binds a txid to a `msg_id`, so a
  /// wrong or hostile value cannot make a claim pass: the transaction it names is fetched and
  /// then has to be shown to carry *this* message's own fragments under the channel key before
  /// anything is read out of it. What an absent or wrong txid costs is a ZEC claim refused for
  /// want of evidence — visible in `ignored_reasons`, never silently treated as paid.
  final String txid;
  final Uint8List body;

  const NjMessageInput({
    required this.msgId,
    required this.kind,
    required this.height,
    required this.txIndex,
    required this.actionIndex,
    required this.fragments,
    required this.txid,
    required this.body,
  });

  @override
  int get hashCode =>
      msgId.hashCode ^
      kind.hashCode ^
      height.hashCode ^
      txIndex.hashCode ^
      actionIndex.hashCode ^
      fragments.hashCode ^
      txid.hashCode ^
      body.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NjMessageInput &&
          runtimeType == other.runtimeType &&
          msgId == other.msgId &&
          kind == other.kind &&
          height == other.height &&
          txIndex == other.txIndex &&
          actionIndex == other.actionIndex &&
          fragments == other.fragments &&
          txid == other.txid &&
          body == other.body;
}

/// A note this wallet owns **or has owned**, with the message that created it and, when it is
/// gone, the message that spent it.
///
/// Spent notes are in this list. They have to be: after a payment the only note of it still in
/// the wallet is the change, and a list of unspent notes alone renders that change as an
/// arrival. The provenance is what a caller groups by to get the payment back —
/// see [`nightjar_replay`] for what is and is not decidable from it.
class NjNote {
  final BigInt position;

  /// The height the note was created at, which is the completion height of `created_by`.
  final int created;
  final String assetId;

  /// Integer units of the asset. Apply `NjAsset::decimals` for display only.
  final BigInt amount;

  /// The spend policy in its text form, e.g. `pk(<ak>)`. Being able to nullify a note is not
  /// the same as being able to open it today: a timelocked note is listed and is not
  /// spendable, which the policy text is what tells the user.
  final String policy;

  /// `ciphertext`, `published` or `recovered` — how the note reached its owner.
  final String source;

  /// False while the note is still this wallet's to spend. True means the channel holds its
  /// nullifier, and `NjAsset::balance` does not count it. This is the field to branch on: it
  /// is read from the channel's own nullifier set, the same set a spend of this note would be
  /// checked against.
  final bool spent;

  /// Lowercase hex `msg_id` of the message that appended this note to the tree. Notes sharing
  /// it were created by one transition.
  ///
  /// For a `published` note this is still the transition that created the note, not the `NOTE`
  /// message that disclosed it — that message moved no money and grouping a receipt under it
  /// would date the receipt wrongly.
  final String createdBy;

  /// How many notes `created_by` consumed and appended **in total**, this wallet's and other
  /// people's alike. `0` inputs is an issuance. The circuit's arity is `MAX_IN` 2 and
  /// `MAX_OUT` 3, so a message can pay a recipient, return change and still carry a third
  /// output.
  ///
  /// These are what say whether the notes in hand are the whole message. A wallet cannot
  /// decrypt an output addressed to somebody else, so an output it does not hold is not a zero
  /// — it is an amount nobody on this side can name. A caller that owns fewer than `outputs`
  /// of a message's outputs must not present the difference as a number.
  final int createdInputs;
  final int createdOutputs;

  /// Lowercase hex `msg_id` of the message that nullified this note, `None` while unspent.
  /// Every note this wallet spent names the message that spent it: the replay records the
  /// nullifiers of each applied message, so "spent" and "spent by whom" arrive together.
  final String? spentBy;

  /// The height that message completed at — when the money left.
  final int? spentHeight;

  /// The same two counts for `spent_by`. `spent_inputs` is the one an authorship test needs:
  /// the wallet authored the payment only if it owned *every* input, and owning one of two is
  /// a co-signed transition, not a send.
  final int? spentInputs;
  final int? spentOutputs;

  const NjNote({
    required this.position,
    required this.created,
    required this.assetId,
    required this.amount,
    required this.policy,
    required this.source,
    required this.spent,
    required this.createdBy,
    required this.createdInputs,
    required this.createdOutputs,
    this.spentBy,
    this.spentHeight,
    this.spentInputs,
    this.spentOutputs,
  });

  @override
  int get hashCode =>
      position.hashCode ^
      created.hashCode ^
      assetId.hashCode ^
      amount.hashCode ^
      policy.hashCode ^
      source.hashCode ^
      spent.hashCode ^
      createdBy.hashCode ^
      createdInputs.hashCode ^
      createdOutputs.hashCode ^
      spentBy.hashCode ^
      spentHeight.hashCode ^
      spentInputs.hashCode ^
      spentOutputs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NjNote &&
          runtimeType == other.runtimeType &&
          position == other.position &&
          created == other.created &&
          assetId == other.assetId &&
          amount == other.amount &&
          policy == other.policy &&
          source == other.source &&
          spent == other.spent &&
          createdBy == other.createdBy &&
          createdInputs == other.createdInputs &&
          createdOutputs == other.createdOutputs &&
          spentBy == other.spentBy &&
          spentHeight == other.spentHeight &&
          spentInputs == other.spentInputs &&
          spentOutputs == other.spentOutputs;
}

/// A payment, proven and framed, waiting for the transport.
///
/// Nothing in it has been broadcast. See [`nightjar_build_pay`].
class NjPayPlan {
  /// Lowercase hex. The id the channel will know this message by, computed from the body — not
  /// chosen. The read path recomputes it and refuses a mismatch, so a plan that did not
  /// satisfy that rule would be unspendable on arrival.
  final String msgId;
  final String assetId;

  /// The `ASSET` message's symbol, empty when nobody has named this asset.
  final String assetSymbol;

  /// Display hint only; no arithmetic on this path applies it.
  final int assetDecimals;

  /// Integer base units to the recipient.
  final BigInt amount;

  /// Integer base units back to this wallet. `0` means the selected notes covered the amount
  /// exactly and the transition has a single output.
  final BigInt change;

  /// `amount + change`: what the consumed notes were worth.
  final BigInt spent;

  /// How many of this wallet's notes this payment nullifies. At most 2 — the circuit's input
  /// arity.
  final int inputs;

  /// The memo fragments, **each exactly 512 bytes**, in order. There are 1-8 of them and they
  /// must all ride one transaction: a reader reassembles a message only from fragments sharing
  /// a txid.
  final List<Uint8List> memos;

  /// Zatoshi to attach to **each** memo output. A Nightjar memo rides an ordinary shielded
  /// output to the channel address, and an output with no value is dust the proposer drops.
  /// Total ZEC cost is this times `memos.length`, plus the Zcash fee, and it is paid to the
  /// channel — not to the Nightjar recipient.
  final BigInt memoValueZatoshi;

  /// Encoded transition body, before framing.
  final int bodyBytes;

  /// The canonical height (`tip − 10`) this plan is anchored at. The anchor ages out of the
  /// channel's anchor window, so a plan is good for roughly that window and not forever.
  final int anchorHeight;
  final int chainTip;

  /// Hash of the verifying key this proof will be checked against: the channel's, which the
  /// key folder had to match before anything was proved.
  final String vkHash;

  /// Wall-clock milliseconds spent proving. ~1 300 on a laptop; more on a phone.
  final int provedMs;

  const NjPayPlan({
    required this.msgId,
    required this.assetId,
    required this.assetSymbol,
    required this.assetDecimals,
    required this.amount,
    required this.change,
    required this.spent,
    required this.inputs,
    required this.memos,
    required this.memoValueZatoshi,
    required this.bodyBytes,
    required this.anchorHeight,
    required this.chainTip,
    required this.vkHash,
    required this.provedMs,
  });

  @override
  int get hashCode =>
      msgId.hashCode ^
      assetId.hashCode ^
      assetSymbol.hashCode ^
      assetDecimals.hashCode ^
      amount.hashCode ^
      change.hashCode ^
      spent.hashCode ^
      inputs.hashCode ^
      memos.hashCode ^
      memoValueZatoshi.hashCode ^
      bodyBytes.hashCode ^
      anchorHeight.hashCode ^
      chainTip.hashCode ^
      vkHash.hashCode ^
      provedMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NjPayPlan &&
          runtimeType == other.runtimeType &&
          msgId == other.msgId &&
          assetId == other.assetId &&
          assetSymbol == other.assetSymbol &&
          assetDecimals == other.assetDecimals &&
          amount == other.amount &&
          change == other.change &&
          spent == other.spent &&
          inputs == other.inputs &&
          memos == other.memos &&
          memoValueZatoshi == other.memoValueZatoshi &&
          bodyBytes == other.bodyBytes &&
          anchorHeight == other.anchorHeight &&
          chainTip == other.chainTip &&
          vkHash == other.vkHash &&
          provedMs == other.provedMs;
}

/// What a settings screen needs to know about a proving-key folder.
///
/// Nightjar's verifying key is 1 784 bytes and arrives over HTTP; its **proving** key is ~83 MiB
/// and arrives from nowhere — nothing serves it and nothing should. This PoC therefore takes a
/// folder path from settings, and this struct is what lets that screen say "sending is
/// unavailable, and here is why" instead of failing at the moment a user presses Send.
class NjProvingKey {
  /// The folder, as resolved.
  final String dir;

  /// The circuit fingerprint, e.g. `constraints=136119;instances=30`. A diagnostic: it says
  /// which circuit shape the keys were made for, not whose ceremony made them.
  final String circuit;

  /// `BLAKE2b-256` of the verifying key beside the proving key, lowercase hex.
  ///
  /// **Compare it with `NjView.vk_hash`.** Two key sets can share a `circuit` string and be
  /// mutually unusable; a payment proved under the wrong one is rejected by every verifier on
  /// the channel *after* the user has paid the Zcash fee to carry it. `nightjar_build_pay`
  /// refuses that case itself, and this field is how a settings screen can refuse it earlier
  /// and more calmly.
  final String vkHash;

  /// Size of `interpreter-v0.pk` in bytes.
  final BigInt provingKeyBytes;

  const NjProvingKey({
    required this.dir,
    required this.circuit,
    required this.vkHash,
    required this.provingKeyBytes,
  });

  @override
  int get hashCode =>
      dir.hashCode ^
      circuit.hashCode ^
      vkHash.hashCode ^
      provingKeyBytes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NjProvingKey &&
          runtimeType == other.runtimeType &&
          dir == other.dir &&
          circuit == other.circuit &&
          vkHash == other.vkHash &&
          provingKeyBytes == other.provingKeyBytes;
}

/// The whole verified view of a channel at one height.
class NjView {
  /// The canonical height this view was closed at: `tip − 10`, never above it. Every number
  /// below is only meaningful here.
  final int height;

  /// The chain tip the view was built against. Report it; do not build against it.
  final int chainTip;
  final String stateRoot;
  final String treeRoot;

  /// `BLAKE2b-256` of the compressed verifying key every proof was checked against, lowercase
  /// hex.
  ///
  /// Compare it with `/api/status`'s `info.vk_hash`. Fetching key and hash from the same server
  /// pins nothing by itself — the value is worth something against a *second* source, or
  /// against one the user holds out of band — but without it on this struct no caller could
  /// pin anything at all, which is what this field exists to fix.
  final String vkHash;

  /// Messages the state machine accepted (applied, published or named).
  final int applied;

  /// Messages it refused, with `ignored_reasons` saying why. Non-zero is normal on a public
  /// channel: anyone may write to it, including with junk.
  final int ignored;

  /// One line per ignored message, `<msg_id> <reason>`, in application order. The reasons are
  /// the state machine's own; they are the only thing that distinguishes "this channel carries
  /// spam" from "this wallet is verifying against the wrong key".
  final List<String> ignoredReasons;

  /// How many of `ignored` were refused because a ZEC claim could not be **checked** rather
  /// than because it was checked and found unpaid.
  ///
  /// Non-zero says this view is knowingly incomplete: the wallet could not reach a Zcash
  /// transaction it needed (no lightwalletd, an unsynced wallet, a server that does not have
  /// it), so an order fill the rest of the channel applied is missing here — and `state_root`
  /// is *expected* to differ from the indexer's as a result. A UI that shows a root mismatch
  /// without showing this turns a fixable configuration problem into what looks like a
  /// dishonest indexer. The matching `ignored_reasons` line ends in "could not be checked: …".
  final int zecUnverifiable;

  /// Messages held back because they sit in blocks that can still reorganise. Non-zero means a
  /// payment is on its way and the balance below is about to change.
  final int previewMessages;

  /// Every note this wallet has ever owned here, unspent and spent alike, ascending by tree
  /// position. See [`nightjar_replay`] for what a caller can and cannot reconstruct from it.
  final List<NjNote> notes;
  final List<NjAsset> assets;

  const NjView({
    required this.height,
    required this.chainTip,
    required this.stateRoot,
    required this.treeRoot,
    required this.vkHash,
    required this.applied,
    required this.ignored,
    required this.ignoredReasons,
    required this.zecUnverifiable,
    required this.previewMessages,
    required this.notes,
    required this.assets,
  });

  @override
  int get hashCode =>
      height.hashCode ^
      chainTip.hashCode ^
      stateRoot.hashCode ^
      treeRoot.hashCode ^
      vkHash.hashCode ^
      applied.hashCode ^
      ignored.hashCode ^
      ignoredReasons.hashCode ^
      zecUnverifiable.hashCode ^
      previewMessages.hashCode ^
      notes.hashCode ^
      assets.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NjView &&
          runtimeType == other.runtimeType &&
          height == other.height &&
          chainTip == other.chainTip &&
          stateRoot == other.stateRoot &&
          treeRoot == other.treeRoot &&
          vkHash == other.vkHash &&
          applied == other.applied &&
          ignored == other.ignored &&
          ignoredReasons == other.ignoredReasons &&
          zecUnverifiable == other.zecUnverifiable &&
          previewMessages == other.previewMessages &&
          notes == other.notes &&
          assets == other.assets;
}

/// Where the replay may look for the Zcash transaction behind a ZEC claim (an order fill).
///
/// Both are optional and an empty string means "not available", which is an ordinary state — a
/// wallet that has not synced has no lightwalletd, and a locked one has no database path. The
/// consequence of handing over neither is not a wrong answer but a *refused* one: claims are
/// reported unchecked and the view says so.
///
/// The Nightjar indexer is deliberately absent from this struct. It is the thing that supplied
/// the message; it is not also allowed to supply the evidence about the message.
class NjZecSources {
  /// Path to this wallet's own `zakura-client-sqlite` database. Tried first: the wallet scans
  /// every block, so a transaction it was a party to costs one local read and no network.
  final String dbPath;

  /// The lightwalletd this wallet syncs against — `GetTransaction` for the transactions it does
  /// not hold, which on a public channel is most of them.
  final String lightwalletdUrl;

  const NjZecSources({required this.dbPath, required this.lightwalletdUrl});

  @override
  int get hashCode => dbPath.hashCode ^ lightwalletdUrl.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NjZecSources &&
          runtimeType == other.runtimeType &&
          dbPath == other.dbPath &&
          lightwalletdUrl == other.lightwalletdUrl;
}
